fragment HomepageParts on Homepage {
  __typename
  siteName
  logo {
    __typename
    url
    path
    bucket
    mimeType
    size
    width
    height
    title
    alt
  }
  navCtaLabel
  navLinks {
    __typename
    label
    href
  }
  hero {
    __typename
    kicker
    eyebrow
    titleLead
    titleAccent
    description
    primaryCtaLabel
    secondaryCtaLabel
    cursorLabel
    cursorYear
    modalTag
    modalTitle
    modalDescription
    backgroundVideo {
      __typename
      sourceType
      url
      vimeoUrl
      path
      bucket
      mimeType
      size
      width
      height
      duration
      posterUrl
      title
      alt
    }
    showreelVideo {
      __typename
      sourceType
      url
      vimeoUrl
      path
      bucket
      mimeType
      size
      width
      height
      duration
      posterUrl
      title
      alt
    }
    scrollLabel
  }
  marqueeItems
  servicesSection {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
    watchLabel
    services {
      __typename
      num
      name
      count
      desc
      items {
        __typename
        tag
        title
        description
        links {
          __typename
          label
          href
        }
        video {
          __typename
          sourceType
          url
          vimeoUrl
          path
          bucket
          mimeType
          size
          width
          height
          duration
          posterUrl
          title
          alt
        }
      }
    }
  }
  processSection {
    __typename
    eyebrow
    title
    steps {
      __typename
      num
      title
      text
    }
  }
  aboutSection {
    __typename
    eyebrow
    title
    description
    photo {
      __typename
      url
      path
      bucket
      mimeType
      size
      width
      height
      title
      alt
    }
    facts {
      __typename
      label
      value
    }
  }
  testimonialsSection {
    __typename
    eyebrow
    title
    badge
    items {
      __typename
      quote
      name
      role
      badge
    }
  }
  partnersSection {
    __typename
    eyebrow
    title
    logos {
      __typename
      name
      href
      logo {
        __typename
        url
        path
        bucket
        mimeType
        size
        width
        height
        title
        alt
      }
    }
  }
  contactSection {
    __typename
    eyebrow
    titleLead
    titleAccent
    titleTrail
    description
    ctaLabel
    email
    backgroundType
    backgroundImage {
      __typename
      url
      path
      bucket
      mimeType
      size
      width
      height
      title
      alt
    }
    backgroundVideo {
      __typename
      sourceType
      url
      vimeoUrl
      path
      bucket
      mimeType
      size
      width
      height
      duration
      posterUrl
      title
      alt
    }
    socialLinks {
      __typename
      label
      href
    }
  }
  footer {
    __typename
    tagline
    menuTitle
    legalTitle
    imprintLabel
    imprintHref
    privacyLabel
    privacyHref
    copyright
    credits
  }
}
